# Form implementation generated from reading ui file '.\view\principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from mplCanvas import MplCanvas, MplCanvas3D
from matplotlib.backends.backend_qtagg import NavigationToolbar2QT as NavigationToolbar
from transfor2D import rotar, escalar, trasladar
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 789)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.app_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.app_title.setGeometry(QtCore.QRect(30, 0, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.app_title.setFont(font)
        self.app_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.app_title.setObjectName("app_title")
        self.verticalLayoutWidget = QtWidgets.QWidget(
            parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(520, 10, 521, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graphic_output = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graphic_output.setContentsMargins(0, 0, 0, 0)
        self.graphic_output.setObjectName("graphic_output")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 481, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(-10, -10, 491, 651))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton_vertix = QtWidgets.QPushButton(
            parent=self.scrollAreaWidgetContents)
        self.pushButton_vertix.setGeometry(QtCore.QRect(370, 30, 91, 31))
        self.pushButton_vertix.setObjectName("pushButton_vertix")
        self.spin_n_vertix = QtWidgets.QSpinBox(
            parent=self.scrollAreaWidgetContents)
        self.spin_n_vertix.setGeometry(QtCore.QRect(280, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spin_n_vertix.setFont(font)
        self.spin_n_vertix.setMinimum(3)
        self.spin_n_vertix.setMaximum(10)
        self.spin_n_vertix.setObjectName("spin_n_vertix")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(20, 25, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.scrollArea_vertix = QtWidgets.QScrollArea(
            parent=self.scrollAreaWidgetContents)
        self.scrollArea_vertix.setGeometry(QtCore.QRect(20, 70, 451, 241))
        self.scrollArea_vertix.setWidgetResizable(True)
        self.scrollArea_vertix.setObjectName("scrollArea_vertix")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(
            QtCore.QRect(0, 0, 449, 239))
        self.scrollAreaWidgetContents_2.setObjectName(
            "scrollAreaWidgetContents_2")
        self.label_areascroll_vertix = QtWidgets.QLabel(
            parent=self.scrollAreaWidgetContents_2)
        self.label_areascroll_vertix.setGeometry(QtCore.QRect(10, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_areascroll_vertix.setFont(font)
        self.label_areascroll_vertix.setObjectName("label_areascroll_vertix")
        self.scrollArea_vertix.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget_2 = QtWidgets.QTabWidget(
            parent=self.scrollAreaWidgetContents)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 320, 451, 301))
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_5 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(350, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pb_rotar_2d = QtWidgets.QPushButton(parent=self.tab_3)
        self.pb_rotar_2d.setGeometry(QtCore.QRect(120, 210, 211, 41))
        self.pb_rotar_2d.setObjectName("pb_rotar_2d")
        self.label_7 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(30, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.te_coord_rotar = QtWidgets.QTextEdit(parent=self.tab_3)
        self.te_coord_rotar.setGeometry(QtCore.QRect(200, 120, 141, 31))
        self.te_coord_rotar.setObjectName("te_coord_rotar")
        self.spin_degrees = QtWidgets.QSpinBox(parent=self.tab_3)
        self.spin_degrees.setGeometry(QtCore.QRect(200, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spin_degrees.setFont(font)
        self.spin_degrees.setMinimum(1)
        self.spin_degrees.setMaximum(359)
        self.spin_degrees.setProperty("value", 1)
        self.spin_degrees.setObjectName("spin_degrees")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.te_vector_transform_2D = QtWidgets.QTextEdit(parent=self.tab_4)
        self.te_vector_transform_2D.setGeometry(QtCore.QRect(290, 70, 131, 31))
        self.te_vector_transform_2D.setObjectName("te_vector_transform_2D")
        self.label_9 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(30, 70, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                  QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.pb_transf_2d = QtWidgets.QPushButton(parent=self.tab_4)
        self.pb_transf_2d.setGeometry(QtCore.QRect(110, 140, 211, 41))
        self.pb_transf_2d.setObjectName("pb_transf_2d")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.te_percent_escalar2D = QtWidgets.QTextEdit(parent=self.tab_5)
        self.te_percent_escalar2D.setGeometry(QtCore.QRect(212, 60, 141, 31))
        self.te_percent_escalar2D.setObjectName("te_percent_escalar2D")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(360, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pb_escalar_2d = QtWidgets.QPushButton(parent=self.tab_5)
        self.pb_escalar_2d.setGeometry(QtCore.QRect(110, 130, 211, 41))
        self.pb_escalar_2d.setObjectName("pb_escalar_2d")
        self.label_4 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(110, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # * Adding custom scripts
        self.pushButton_vertix.clicked.connect(self.createTextEditOnScrollArea)

        # sc = MplCanvas(self)
        sc = MplCanvas3D(self)
        toolbar = NavigationToolbar(sc)
        self.graphic_output.addWidget(toolbar)
        self.graphic_output.addWidget(sc)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.app_title.setText(_translate("MainWindow", "Transformaciones"))
        self.pushButton_vertix.setText(_translate("MainWindow", "OK"))
        self.label_2.setText(_translate(
            "MainWindow", "Selecciona el numero de vertices"))
        self.label_areascroll_vertix.setText(_translate(
            "MainWindow", "Ingrese las coordenadas en los espacios en blanco. Ej: 13, 4"))
        self.label_5.setText(_translate(
            "MainWindow", "Ingrese el valor a rotar"))
        self.label_6.setText(_translate("MainWindow", "grados (°)"))
        self.pb_rotar_2d.setText(_translate("MainWindow", "OK"))
        self.label_7.setText(_translate("MainWindow", "Ingrese la coordenada"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(
            self.tab_3), _translate("MainWindow", "ROTAR"))
        self.label_9.setText(_translate(
            "MainWindow", "Introduzca el vector (x, y): Ej. 13, 4"))
        self.pb_transf_2d.setText(_translate("MainWindow", "OK"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(
            self.tab_4), _translate("MainWindow", "TRASLADAR"))
        self.label_3.setText(_translate("MainWindow", "%"))
        self.pb_escalar_2d.setText(_translate("MainWindow", "OK"))
        self.label_4.setText(_translate("MainWindow", "Porcentaje"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(
            self.tab_5), _translate("MainWindow", "ESCALAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab), _translate("MainWindow", "FIGURA 2D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_2), _translate("MainWindow", "FIGURA 3D"))

    def checkValueNumVertix(self):
        '''Checa el valor del numero de vertices'''
        self.spin_n_vertix.value()
        pass

    def createTextEditOnScrollArea(self):
        global array_coords_vertix
        array_coords_vertix = []
        n_vertix = self.spin_n_vertix.value()
        print(type(n_vertix))
        for i in range(n_vertix):
            array_coords_vertix.append(
                QtWidgets.QTextEdit(parent=self.scrollArea_vertix))
            # array_coords_vertix[i]
            pass


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
